{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ .Release.Name }}-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ingress
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.ingress.namespace | default .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.backend.path }}
        pathType: {{ .Values.ingress.backend.pathType }}
        backend:
          service:
            name: {{ .Values.ingress.backend.service.name }}
            port:
              number: {{ .Values.ingress.backend.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
{{ end }}